[package]
name = "phy_numerical"
version = "0.1.2"
authors = ["SyedUzairAhmed <syeduzair03@hotmail.com>"]
edition = "2019"
license = "MIT"
description = "some numericals"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
